### ISSUE TITLE
NullPointerException when profiling with JER

### ISSUE THREAD

**Issue by DimiDimit** [DimiDimit/DAMTest#6]
When running the /profile command, a NullPointerException is thrown. This may or may not be this mod's fault, more research is required. [This is the crash report.](https://github.com/DimiDimit/DAMTest/files/3238382/crash-2019-05-30_22.04.56-server.txt) In short:

	java.lang.NullPointerException: Exception in server tick loop
		at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:869)
		at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
		at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)

**Comment by DimiDimit** [comment]
This only seems to happen in the development environment and doesn't seem related to this mod, so I'm closing it.
